"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

setup(
    name='WaveGrowl',
    app=['wavegrowl.py'],
    author='Alec Thomas',
    author_email='alec@swapoff.org',
    description='Google Wave Growl notifier',
    version='0.1',
    data_files=['wavegrowl.png', 'wavegrowlmenubar.png',
                'wavegrowlmenubardisabled.png'],
    options=dict(py2app=dict(
        plist=dict(
            LSUIElement=True,
            CFBundleGetInfoString='Google Wave Growl notifier',
            CFBundleIdentifier='com.google.wavegrowl',
        ),
        iconfile='wavegrowl.icns',
    )),
    setup_requires=[
        'keyring',
        'py-Growl',
        'py2app',
        'pyobjc-framework-Cocoa',
    ],
    entry_points="""
    [console_scripts]
    wavegrowl = wavegrowl:main
    """,
)
